name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
      - name: Install dependencies
        run: yarn install
      - name: ERC20 build
        run: yarn build:erc20
      - name: ERC20 test
        run: yarn test:erc20
      - name: Atomic NFT build
        run: yarn build:atomic-nft
      - name: Atomic NFT run tests
        run: yarn test:atomic-nft
      - name: PST build
        run: yarn build:pst
      - name: PST run tests
        run: yarn test:pst
      - name: Staking contract build
        run: yarn build:example:staking
      - name: Staking contract test
        run: yarn test:example:staking
